[dev]
  command = "yarn dev"
  autoLaunch = false

[build]
  command = "yarn build"
  functions = "functions/"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
